// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacationRegister.Data;

#nullable disable

namespace VacationRegister.Migrations
{
    [DbContext(typeof(VacRegDbContext))]
    [Migration("20240414145026_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VacationRegister.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Economics"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Administration"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Development"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Sales"
                        });
                });

            modelBuilder.Entity("VacationRegister.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EmpId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            BirthDate = new DateTime(2001, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "Andreas",
                            LastName = "Fors"
                        },
                        new
                        {
                            EmpId = 2,
                            BirthDate = new DateTime(1993, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            FirstName = "Johanna",
                            LastName = "Marklund"
                        },
                        new
                        {
                            EmpId = 3,
                            BirthDate = new DateTime(1995, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            FirstName = "Axel",
                            LastName = "Wennström"
                        },
                        new
                        {
                            EmpId = 4,
                            BirthDate = new DateTime(1992, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            FirstName = "Fredrik",
                            LastName = "Engström"
                        },
                        new
                        {
                            EmpId = 5,
                            BirthDate = new DateTime(1990, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            FirstName = "Nicklas",
                            LastName = "Karlsson"
                        },
                        new
                        {
                            EmpId = 6,
                            BirthDate = new DateTime(1995, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "Nadine",
                            LastName = "Ullström"
                        },
                        new
                        {
                            EmpId = 7,
                            BirthDate = new DateTime(2002, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "Nino",
                            LastName = "Olivetto"
                        },
                        new
                        {
                            EmpId = 8,
                            BirthDate = new DateTime(1980, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            FirstName = "Roger",
                            LastName = "Zheng"
                        });
                });

            modelBuilder.Entity("VacationRegister.Models.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkEmpId")
                        .HasColumnType("int");

                    b.Property<int>("FkLeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LeaveNotes")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveId");

                    b.HasIndex("FkEmpId");

                    b.HasIndex("FkLeaveTypeId");

                    b.ToTable("Leaves");

                    b.HasData(
                        new
                        {
                            LeaveId = 1,
                            CreateDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 3,
                            FkLeaveTypeId = 5,
                            LeaveNotes = "AI-course",
                            StartDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeaveId = 2,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 1,
                            FkLeaveTypeId = 1,
                            LeaveNotes = "Vacation",
                            StartDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeaveId = 3,
                            CreateDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 1,
                            FkLeaveTypeId = 2,
                            LeaveNotes = "Day care closed",
                            StartDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeaveId = 4,
                            CreateDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 3,
                            FkLeaveTypeId = 4,
                            LeaveNotes = "Fever",
                            StartDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeaveId = 5,
                            CreateDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 2,
                            FkLeaveTypeId = 2,
                            LeaveNotes = "children with fever",
                            StartDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeaveId = 6,
                            CreateDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkEmpId = 7,
                            FkLeaveTypeId = 3,
                            LeaveNotes = "Doctors appointment",
                            StartDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VacationRegister.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("LeaveDescr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeofLeave")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            LeaveDescr = "Ordinary vacation",
                            TypeofLeave = "Holiday"
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            LeaveDescr = "Time off to take care of children",
                            TypeofLeave = "Child-care"
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            LeaveDescr = "For things like hospital appointments",
                            TypeofLeave = "Personal"
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            LeaveDescr = "If you are to sick to work today",
                            TypeofLeave = "Sick"
                        },
                        new
                        {
                            LeaveTypeId = 5,
                            LeaveDescr = "Education",
                            TypeofLeave = "Education"
                        });
                });

            modelBuilder.Entity("VacationRegister.Models.Employee", b =>
                {
                    b.HasOne("VacationRegister.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("VacationRegister.Models.Leave", b =>
                {
                    b.HasOne("VacationRegister.Models.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("FkEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacationRegister.Models.LeaveType", "LeaveType")
                        .WithMany("Leaves")
                        .HasForeignKey("FkLeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("VacationRegister.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("VacationRegister.Models.Employee", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("VacationRegister.Models.LeaveType", b =>
                {
                    b.Navigation("Leaves");
                });
#pragma warning restore 612, 618
        }
    }
}
